services:
  - type: web
    name: company-dashboard
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 
      - key: TABLEAU_DASHBOARD_URL
        value: https://public.tableau.com/app/profile/niksa.derek/viz/FunnelAnalysis_17472437058310/TableView?publish=yes
      - key: ENABLE_TABLEAU_AUTO_EXTRACT
        value: true 